### ISSUE TITLE
Webspace: Anbieterübersicht

### ISSUE THREAD

**Issue by GKohlmann** [SimonDetmer/WebProg_Abschlussarbeit#2]

**Comment by GKohlmann** [comment]
[Webspace_Anbieterübersicht.pdf](https://github.com/SimonDetmer/WebProg_Abschlussarbeit/files/3142955/Webspace_Anbieterubersicht.pdf)

**Comment by GKohlmann** [comment]
Anmeldung

**Comment by SimonDetmer** [comment]
bplaced-Webspace wurde eingereichtet. Unsere ist jetzt [hier](http://kohldetweb19.bplaced.net/) zu erreichen. 

**FTP-Daten:**
- Server: ftp://kohldetweb19.bplaced.net
- Nutzer: kohldetweb19
- Passwort: Folgt per whatsapp

**bplaced-Zugang:**
- E-Mail: simon.detmer@googlmail.com
- Passwort: Folgt per whatsapp

**Comment by GKohlmann** [comment]
ok
