### ISSUE TITLE
Namensfindung

### ISSUE THREAD

**Issue by SimonDetmer** [SimonDetmer/WebProg_Abschlussarbeit#5]
Mir ist aufgefallen, dass wir noch keinen Namen für unser Produkt haben. Das sollten wir noch im Auge behalten. Vielleicht überlegen wir uns sowas kurzes, markantes aber verspieltes wie "zalando" oder "trivago" oder so?

**Comment by GKohlmann** [comment]
gute Idee, Domain-Name wird nicht umzusetzen sein

**Comment by SimonDetmer** [comment]
**1. Idee: abalobo** 
Abgeleitet von abahlobo, das bedeutet "Freunde" in Xhosa (Sprache des gleichnamigen Volks in Südafrika)

**2. Idee: SiDeKo** bzw. **DeKo**
Fantasie-Wörter aus unseren Initialien. (Ich hatte versucht "Gr" einzubinden, hab aber leider keinen guten Namen hinbekommen :))

**Comment by GKohlmann** [comment]
abalobo
